import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Workbook, SpreadsheetFile, FileBlob } from '@oai/artifact-tool';
const here=path.dirname(fileURLToPath(import.meta.url));
const source=JSON.parse(await fs.readFile(path.join(here,'汇总表数据.json'),'utf8'));
const outputPath=path.join(here,'../结果/三方法汇总.xlsx');
let workbook,sheet;
const existing=await fs.access(outputPath).then(()=>true,()=>false);
if(existing && !process.argv.includes('--from-data')){
  workbook=await SpreadsheetFile.importXlsx(await FileBlob.load(outputPath));
  sheet=workbook.worksheets.getItem('三方法汇总');
  sheet.getRange('A1').values=[['MLE、MMLE、WMLE 参数估计汇总']];
  sheet.getRange('A11:A15').values=[['MMLE']];
  sheet.getRange('A24').values=[['MLE 是上一批原文域有限驻点局部极大解；MMLE 固定 γ 为样本最小值并删除该观测。各方法有效子集不同。']];
}else{
workbook=Workbook.create();sheet=workbook.worksheets.add('三方法汇总');
sheet.showGridLines=false;
const font='Arial';
sheet.getRange('A1:O25').format.font={name:font,size:11,color:'#26313A'};
sheet.getRange('A1').values=[['MLE、MMLE、WMLE 参数估计汇总']];
sheet.getRange('A1').format.font={name:font,size:15,bold:true};
sheet.getRange('A2').values=[['真值 β = 2，η = 1000，γ = 1000；每个 n 使用同一批 1200 组样本。']];
sheet.getRange('A2').format.font={name:font,size:11,color:'#5F6570'};
sheet.getRange('A3:O3').format.borders={bottom:{style:'thin',color:'#B8C2CA'}};
sheet.getRange('A5:O5').values=[['方法','n','总组数','有效解','有解率','β Bias','β SD','β RMSE','η Bias','η SD','η RMSE','γ Bias','γ SD','γ RMSE','联合 RMSE']];
sheet.getRange('A6:O20').values=source.rows;
sheet.getRange('E6').formulas=[['=D6/C6']];sheet.getRange('E6:E20').fillDown();
sheet.getRange('O6').formulas=[['=SQRT(H6^2+K6^2+N6^2)']];sheet.getRange('O6:O20').fillDown();
sheet.getRange('A5:O5').format={fill:'#3D4A56',font:{name:font,size:11,color:'#FFFFFF',bold:true},horizontalAlignment:'center',verticalAlignment:'center',rowHeight:30};
sheet.getRange('A6:O20').format.rowHeight=26;
sheet.getRange('B6:O20').format.horizontalAlignment='right';
sheet.getRange('B6:D20').setNumberFormat('0');sheet.getRange('E6:E20').setNumberFormat('0.00%');
sheet.getRange('F6:H20').setNumberFormat('0.000');sheet.getRange('I6:O20').setNumberFormat('0.00');
sheet.getRange('A6:A10').format.font={name:font,size:11,bold:true,color:'#5F6570'};
sheet.getRange('A11:O15').format.fill='#F2F6F9';sheet.getRange('A11:A15').format.font={name:font,size:11,bold:true,color:'#345D7E'};
sheet.getRange('A16:A20').format.font={name:font,size:11,bold:true,color:'#986237'};
for(const row of [10,15,20])sheet.getRange(`A${row}:O${row}`).format.borders={bottom:{style:'thin',color:'#CFD7DE'}};
sheet.getRange('A:A').format.columnWidthPx=115;sheet.getRange('B:B').format.columnWidthPx=50;
sheet.getRange('C:D').format.columnWidthPx=70;sheet.getRange('E:E').format.columnWidthPx=87;
sheet.getRange('F:H').format.columnWidthPx=85;sheet.getRange('I:N').format.columnWidthPx=91;sheet.getRange('O:O').format.columnWidthPx=101;
sheet.getRange('A22').values=[['Bias = mean(估计−真值)；SD 使用 ddof = 0；RMSE 使用全部有效估计，未按显示范围截尾。']];
sheet.getRange('A23').values=[['联合 RMSE = √(β RMSE² + η RMSE² + γ RMSE²)，保留原始参数单位，数值主要由 η 与 γ 主导。']];
sheet.getRange('A24').values=[['MLE 是上一批原文域有限驻点局部极大解；MMLE 固定 γ 为样本最小值并删除该观测。各方法有效子集不同。']];
sheet.getRange('A25').values=[['Kundu–Raqab (2009)，§2，pp.1840–1841： https://home.iitk.ac.in/~kundu/paper154.pdf']];
sheet.getRange('A22:O25').format.font={name:font,size:10,color:'#5F6570'};
sheet.getRange('A22:O25').format.rowHeight=23;
const table=sheet.tables.add('A5:O20',true,'MethodSummary');table.showFilterButton=true;
}
const inspected=await workbook.inspect({kind:'region',sheetId:sheet.name,range:'A5:O20',maxChars:6500,tableMaxRows:16,tableMaxCols:15});
await fs.writeFile(path.join(here,'工作簿检查.txt'),inspected.ndjson);
const formulaScan=await workbook.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NUM!|#NAME\\?',options:{useRegex:true,maxResults:10},maxChars:2000});
await fs.writeFile(path.join(here,'公式错误检查.txt'),formulaScan.ndjson);
const preview=await workbook.render({sheetName:sheet.name,autoCrop:'all',scale:1,format:'png'});
await fs.writeFile(path.join(here,'汇总表预览.png'),new Uint8Array(await preview.arrayBuffer()));
const xlsx=await SpreadsheetFile.exportXlsx(workbook);
await xlsx.save(outputPath);
console.log('XLSX exported; all 15 summary rows inspected and the only sheet rendered.');
